openapi: 3.0.3
info:
  title: Task Manager API
  description: Api for the task manager toool.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: "greeting"
    description: "Greeting endpoints"
paths:
  /api/v1/greeting:
    get:
      summary: Returns a greeting.
      tags:
        - "greeting"
      operationId: "greeting"
      parameters:
        - name: "name"
          in: "query"
          schema:
            type: "string"
            default: "stranger"
      responses:
        '200':
          description: Greeting content
          content:
            application/json:
              schema:
                type: string