/**
 * Task Manager API
 * Api for the task manager toool.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Task information
 */
export interface Task { 
    id?: number;
    title?: string;
    description?: string;
    /**
     * the user creator of the task
     */
    owner?: string;
    creationDateTime?: string;
    status?: Task.StatusEnum;
}
export namespace Task {
    export type StatusEnum = 'PENDING' | 'COMPLETE';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Complete: 'COMPLETE' as StatusEnum
    };
}


