/**
 * Task Manager API
 * Api for the task manager toool.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Task } from './task';


export interface TaskList { 
    count?: number;
    tasks?: Array<Task>;
}

